---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: exporter
  labels:
    app: exporter
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      name: http
      port: 9187
      targetPort: 9187
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: exporter
          image: prometheuscommunity/postgres-exporter
          imagePullPolicy: "Always"
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://sk:00000000@db:5432/test?sslmode=disable"
        - name: db
          image: postgres:9.6
          imagePullPolicy: "IfNotPresent"
          args:
            - -c
            - max_connections=1000
          ports:
            - containerPort: 5432
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
            - name: POSTGRES_PASSWORD
              value: "00000000"
            - name: POSTGRES_DB
              value: "test"
            - name: POSTGRES_USER
              value: "sk"
