apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  labels:
    app: express
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: cr.yandex/crpkm2iuoqei95gkbii8/express-db:latest
        imagePullPolicy: Always # !!!
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: PORT
          value: "4000"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: secret
              key: value
      