version: '3.7'
services:
  express:
    image: express-db:latest
    depends_on:
      - redis
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3000:3000"
  redis:
    image: redis
    ports:
      - "6379:6379"
